package main

import (
	"os/exec"
	"testing"
)

// regressionClasses mirrors testdata/regressions/: one before/after pair per
// known divergence class, each with a real recorded history generated by
// tools/gen-regressions. This is the PRD's core detection-coverage metric
// (§7: "6/6 classes caught").
var regressionClasses = []string{
	"reorder-activity",
	"removed-activity",
	"changed-timer",
	"renamed-activity",
	"added-command",
	"time-now-regression",
}

func TestRegressionBattery(t *testing.T) {
	for _, class := range regressionClasses {
		t.Run(class, func(t *testing.T) {
			corpusDir := "../../testdata/regressions/" + class + "/corpus"

			t.Run("before_replays_clean", func(t *testing.T) {
				cmd := exec.Command(binPath, "replay",
					"--corpus", corpusDir,
					"--registrations", "../../testdata/regressions/"+class+"/before",
				)
				out, _ := cmd.CombinedOutput()
				if cmd.ProcessState.ExitCode() != 0 {
					t.Fatalf("expected the unmodified workflow to replay clean, got exit %d\noutput:\n%s",
						cmd.ProcessState.ExitCode(), out)
				}
			})

			t.Run("after_diverges", func(t *testing.T) {
				// fail-on=any so a divergence is exit 1 regardless of whether
				// the fixture history is open or closed — this test is about
				// detection, not the open/closed severity split.
				cmd := exec.Command(binPath, "replay",
					"--corpus", corpusDir,
					"--registrations", "../../testdata/regressions/"+class+"/after",
					"--fail-on", "any",
				)
				out, _ := cmd.CombinedOutput()
				if cmd.ProcessState.ExitCode() != 1 {
					t.Fatalf("expected the regressed workflow to diverge (exit 1 under fail-on=any), got exit %d\noutput:\n%s", cmd.ProcessState.ExitCode(), out)
				}
			})
		})
	}
}
